# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "CV"
#  url = "files/cv.pdf"
#  weight = 10

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20
  
[[main]]
  name = "Policy Work"
  url = "#projects"
  weight = 30
  
[[main]]
  name = "Working papers"
  url = "#WP"
  weight = 40

[[main]]
    name = "Work In Progress"
    url = "#WIP"
    weight = 50

[[main]]
    name = "Teaching"
    url = "#teaching"
    weight = 60
    
[[main]]
  name = "Selected Awards"
  url = "#awards"
  weight = 70


[[main]]
  name = "Useful Codes"
  url = "#codes"
  weight = 80
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
